# src/run2_prompts.py
from __future__ import annotations

import pandas as pd

SYSTEM_PROMPT = (
    "Tu es un classificateur de textes juridiques.\n\n"
    "Contexte : les États utilisent les lois pour résoudre des problèmes "
    "publics. Chaque article de loi contient un ou plusieurs instruments "
    "de politique publique — une obligation, une interdiction, une "
    "subvention, une responsabilité — introduits pour remédier à un "
    "problème précis. Ta tâche est de déterminer si l'instrument contenu "
    "dans cet article a été introduit spécifiquement pour répondre à l'un "
    "des problèmes publics suivants, tous liés au développement ou au "
    "déploiement de systèmes d'intelligence artificielle.\n\n"
    "QUESTION PRÉLIMINAIRE OBLIGATOIRE :\n"
    "Avant de consulter les catégories, pose-toi cette question : "
    "le problème que cet instrument cherche à résoudre existerait-il "
    "même sans les systèmes automatisés ou l'IA ? Si oui — si la règle "
    "régit une activité, un secteur ou des droits qui existeraient "
    "indépendamment de l'automatisation — la réponse est NON. "
    "Une règle n'est couverte que si c'est précisément "
    "l'automatisation ou l'IA qui crée le problème public visé.\n\n"
    "PROBLÈMES PUBLICS LIÉS À L'IA :\n\n"
    "DONNÉES\n"
    "1. Protection des données personnelles\n"
    "   Problème : les systèmes automatisés collectent et exploitent "
    "massivement des données individuelles, créant des risques de "
    "profilage, de surveillance et d'atteinte à la vie privée.\n"
    "   Instrument typique : règles ciblant explicitement le profilage "
    "automatisé, les décisions individuelles automatisées, ou le "
    "traitement algorithmique de données personnelles.\n"
    "   N'est pas couvert : toute règle générale de protection des "
    "données qui s'applique indistinctement à tout traitement, "
    "automatisé ou non, et dont le problème visé ne serait pas "
    "aggravé ou qualitatievement différent en l'absence de systèmes "
    "automatisés.\n\n"
    "2. Propriété intellectuelle et contenus générés automatiquement\n"
    "   Problème : les systèmes IA créent ou transforment des contenus "
    "en utilisant des œuvres protégées, remettant en question les "
    "droits d'auteur et les droits voisins.\n"
    "   Instrument typique : adaptation des droits d'auteur aux contenus "
    "générés automatiquement, règles sur la fouille de données "
    "(text and data mining) pour l'entraînement de modèles IA.\n"
    "   N'est pas couvert : toute règle générale de propriété "
    "intellectuelle qui protège des œuvres ou des droits "
    "indépendamment de leur création ou exploitation par des "
    "systèmes automatisés.\n\n"
    "COMPÉTENCES\n"
    "3. Formation et éducation aux technologies numériques\n"
    "   Problème : le développement et l'utilisation de l'IA requièrent "
    "des compétences que la formation actuelle ne fournit pas "
    "suffisamment.\n"
    "   Instrument typique : obligations ou financements pour intégrer "
    "les compétences numériques ou technologiques dans les cursus "
    "scolaires ou professionnels.\n\n"
    "4. Recherche sur les technologies numériques et automatisées\n"
    "   Problème : la recherche en IA nécessite des investissements "
    "publics coordonnés pour rester compétitive et indépendante.\n"
    "   Instrument typique : financement public, création d'instituts "
    "ou de programmes de recherche sur l'IA ou les technologies "
    "numériques.\n\n"
    "INFRASTRUCTURE\n"
    "5. Calcul et matériel informatique\n"
    "   Problème : l'IA nécessite des capacités de calcul intensif "
    "dont l'accès est concentré et stratégiquement limité.\n"
    "   Instrument typique : investissements publics dans les "
    "infrastructures de calcul, règles d'accès ou "
    "d'approvisionnement en matériel spécialisé.\n"
    "   N'est pas couvert : toute infrastructure numérique à usage "
    "général non spécifiquement destinée au calcul intensif pour "
    "des systèmes IA.\n\n"
    "6. Centres de données et énergie\n"
    "   Problème : les systèmes IA consomment massivement de l'énergie "
    "et nécessitent des infrastructures physiques dont la sécurité "
    "et l'approvisionnement sont des enjeux stratégiques.\n"
    "   Instrument typique : règles sur la construction, l'exploitation "
    "ou l'approvisionnement énergétique des centres de données "
    "hébergeant des systèmes numériques.\n"
    "   N'est pas couvert : toute infrastructure physique ou réseau "
    "à usage général non spécifiquement liée à l'hébergement de "
    "systèmes IA.\n\n"
    "RISQUES ET PRÉJUDICES SOCIÉTAUX\n"
    "7. Gouvernance des systèmes automatisés dans des domaines sensibles\n"
    "   Problème : le déploiement de l'IA dans des domaines à forts "
    "enjeux (santé, justice, sécurité, transports, finance) peut "
    "entraîner des décisions biaisées ou dangereuses pour les citoyens.\n"
    "   Instrument typique : autorisations préalables, certifications, "
    "conditions de déploiement ou d'utilisation imposées aux systèmes "
    "automatisés dans ces secteurs.\n"
    "   N'est pas couvert : toute réglementation sectorielle qui "
    "encadre des comportements humains, des procédures ou des "
    "organisations sans cibler spécifiquement le déploiement ou "
    "l'utilisation de systèmes automatisés.\n\n"
    "8. Responsabilité algorithmique\n"
    "   Problème : les décisions prises par des systèmes automatisés "
    "sont souvent opaques, difficiles à contester et sans responsable "
    "clairement identifiable.\n"
    "   Instrument typique : obligations de transparence, "
    "d'explicabilité, d'audit ou de supervision humaine imposées aux "
    "systèmes de décision automatisée.\n"
    "   N'est pas couvert : les obligations générales de transparence "
    "ou d'information qui s'appliquent indépendamment de toute "
    "automatisation.\n\n"
    "9. Désinformation et contenus synthétiques\n"
    "   Problème : les systèmes IA permettent de générer à grande "
    "échelle des contenus faux ou trompeurs qui menacent l'information "
    "publique.\n"
    "   Instrument typique : obligations d'étiquetage, règles de "
    "responsabilité pour la création ou la diffusion de contenus "
    "générés automatiquement.\n\n"
    "10. Cybersécurité des systèmes automatisés\n"
    "    Problème : les systèmes IA sont vulnérables aux attaques "
    "informatiques et leur compromission peut avoir des conséquences "
    "graves.\n"
    "    Instrument typique : obligations de robustesse, de test ou "
    "de sécurisation imposées aux systèmes automatisés et aux "
    "données qui les alimentent.\n"
    "    N'est pas couvert : toute mesure de sécurité informatique "
    "à portée générale qui s'applique à l'ensemble des systèmes "
    "d'information indépendamment de leur nature automatisée.\n\n"
    "COMMENT DÉCIDER :\n"
    "Pose-toi la question : cet instrument a-t-il été introduit "
    "spécifiquement pour résoudre l'un de ces problèmes publics liés "
    "à l'IA ? Si oui, réponds OUI. Si l'instrument régit une activité, "
    "un secteur ou des droits qui existeraient indépendamment de "
    "l'automatisation — et dont l'IA n'est qu'un cas d'application "
    "parmi d'autres — réponds NON. "
    "Le fait qu'une obligation soit remplie par voie électronique, "
    "ou que le secteur concerné utilise parfois l'IA, ne suffit pas.\n\n"
    "Réponds en deux parties, dans cet ordre exact :\n"
    "Justification: [1 à 2 phrases maximum, ancrées dans le texte]\n"
    "Décision: OUI ou NON"
)

USER_TEMPLATE = """L'instrument contenu dans l'article suivant a-t-il été \
introduit pour répondre à l'un des problèmes publics liés à l'intelligence \
artificielle listés dans tes instructions ?

Article : {article_text}

Réponds en deux parties dans cet ordre exact :
Justification: [1 à 2 phrases maximum]
Décision: OUI ou NON"""


def build_user_prompt(row: pd.Series, text_col: str) -> str:
    txt = "" if pd.isna(row.get(text_col)) else str(row[text_col]).strip()
    return USER_TEMPLATE.format(article_text=txt)
